### ISSUE TITLE
If the itemHeight is inconstant, going back to first index fails

### ISSUE THREAD

**Issue by jannunen** [HasanAlyazidi/react-native-sectionlist-sidebar#2]
Sometimes item heights might change (eg. items without pictures and using two columns).

When coming back to first index via the sidebar an error is generated:

`scrollToIndex out of range: -1 vs 64`

A quick fix would be to make sure that scrollToIndex doesn't get too low values.

**Comment by HasanAlyazidi** [comment]
All items must have the same height and two columns in a row are not supported yet.
PRs are welcome.

**Comment by jannunen** [comment]
Hi. 

Two columns can be done, as I have done it already. Would it be possible for you to add the fix that scrollToIndex doesn't go negative.

If not, then I'll do it and send a PR. 

Thanks =)

**Comment by HasanAlyazidi** [comment]
Please share your code on [Expo Snack](https://snack.expo.io), so i can help easily.

**Comment by myomyintaung1411** [comment]
Hello sir how to image in data

**Comment by HasanAlyazidi** [comment]
Hello @myomyintaung1411,

Please create a new issue since your issue is completely different from this issue (#2).

**Comment by HasanAlyazidi** [comment]
@jannunen fixed with 2ecd660. please install `^1.0.4`.
